//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const OTP_VERIFIED = 'OTP_VERIFIED';

export const PROFILE_VERIFIED = 'PROFILE_VERIFIED';

export const SET_TOKEN = 'SET_TOKEN';
export const GET_TOKEN = 'GET_TOKEN';

export const GET_JOB_TYPES = 'GET_JOB_TYPES';
export const FAILURE_JOB_TYPES = 'FAILURE_JOB_TYPES';

export const HIRED_JOB_REQUEST = 'HIRED_JOB_REQUEST';
export const HIRED_JOB_RESPONSE = 'HIRED_JOB_RESPONSE';
export const HIRED_JOB_FAILED = 'HIRED_JOB_FAILED';

export const FIND_JOBS_REQUEST = 'FIND_JOBS_REQUEST';
export const FIND_JOBS_RESPONSE = 'FIND_JOBS_RESPONSE';
export const FIND_JOBS_FAILED = 'FIND_JOBS_FAILED';

export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST';
export const CREATE_PROFILE_RESPONSE = 'CREATE_PROFILE_RESPONSE';
export const CREATE_PROFILE_FAILED = 'CREATE_PROFILE_FAILED';

export const JOB_DETAILS_REQUEST = 'JOB_DETAILS_REQUEST';
export const JOB_DETAILS_RESPONSE = 'JOB_DETAILS_RESPONSE';
export const JOB_DETAILS_FAILED = 'JOB_DETAILS_FAILED';
export const CLEAR_JOB_DETAIL = 'CLEAR_JOB_DETAIL';

export const REQUEST_LOCATION = 'REQUEST_LOCATION';
export const SAVE_LOCATION = 'SAVE_LOCATION';
export const FAILURE_LOCATION = 'FAILURE_LOCATION';

export const GET_MY_JOBS_REQUEST = 'GET_MY_JOBS_REQUEST';
export const GET_MY_JOBS_RESPONSE = 'GET_MY_JOBS_RESPONSE';
export const GET_MY_JOBS_FAILED = 'GET_MY_JOBS_FAILED';

export const APPLY_JOB_REQUEST = 'APPLY_JOB_REQUEST';
export const APPLY_JOB_RESPONSE = 'APPLY_JOB_RESPONSE';
export const APPLY_JOB_FAILED = 'APPLY_JOB_FAILED';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_APP_INTRO = 'CHANGE_APP_INTRO';

export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_RESPONSE = 'OTP_RESPONSE';
export const OTP_FAILED = 'OTP_FAILED';

export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const GET_INFO_RESPONSE = 'GET_INFO_RESPONSE';
export const GET_INFO_FAILED = 'GET_INFO_FAILED';

export const GET_BANNER_REQUEST = 'GET_BANNER_REQUEST';
export const GET_BANNER_RESPONSE = 'GET_BANNER_RESPONSE';
export const GET_BANNER_FAILED = 'GET_BANNER_FAILED';

export const GET_DISTINCTJOBTYPES_REQUEST = 'GET_DISTINCTJOBTYPES_REQUEST';
export const GET_DISTINCTJOBTYPES_RESPONSE = 'GET_DISTINCTJOBTYPES_RESPONSE';
export const GET_DISTINCTJOBTYPES_FAILED = 'GET_DISTINCTJOBTYPES_FAILED';

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED';
export const GET_NOTIFICATIONS_RESPONSE = 'GET_NOTIFICATIONS_RESPONSE';

export const GET_EARNINGS_REQUEST = 'GET_EARNINGS_REQUEST';
export const GET_EARNINGS_RESPONSE = 'GET_EARNINGS_RESPONSE';
export const GET_EARNINGS_FAILED = 'GET_EARNINGS_FAILED';

export const GET_EARNINGDETAILS_REQUEST = 'GET_EARNINGDETAILS_REQUEST';
export const GET_EARNINGDETAILS_RESPONSE = 'GET_EARNINGDETAILS_RESPONSE';
export const GET_EARNINGDETAILS_FAILED = 'GET_EARNINGDETAILS_FAILED';
